version: '3'

services:
  pgdatabase:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=pagila_entertainment
    volumes:
      - ./pagila_postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - pagila-network

  pgadminPagila:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - ./data_pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - pagila-network
    depends_on:
      - pgdatabase 

networks:
  pagila-network:
    name: pagila-network
    driver: bridge

volumes:
  pagila_postgres_data:
  data_pgadmin:
